// Type Imports
import type { Person } from '@/features/nexacrm/types/apps/person-types'

// Data Imports
import { scaleCompanies } from '@/features/nexacrm/fake-db/apps/companies'

export type PersonSeed = Omit<Person, 'createdAt' | 'updatedAt'> & {
  createdMinutesAgo: number
  updatedMinutesAgo: number
}

const FIRST_NAMES = [
  'Sophia',
  'Liam',
  'Mia',
  'Ethan',
  'Ava',
  'Noah',
  'Isabel',
  'Lucas',
  'Amara',
  'Kenji',
  'Priya',
  'Mateo',
  'Hannah',
  'Omar',
  'Freya',
  'Diego',
  'Nina',
  'Tobias',
  'Leila',
  'Jonas',
  'Clara',
  'Andre',
  'Yuki',
  'Marcus',
  'Elif',
  'Rafael',
  'Ingrid',
  'Samir'
]

const LAST_NAMES = [
  'Carter',
  'Patel',
  'Chen',
  'Brooks',
  'Okafor',
  'Lindqvist',
  'Duarte',
  'Watanabe',
  'Novak',
  'Silva',
  'Fischer',
  'Moreau',
  'Haddad',
  'Bergman',
  'Rossi',
  'Nakamura',
  'Vargas',
  'Whitfield',
  'Castillo',
  'Ahmed',
  'Kowalski',
  'Bianchi',
  'Sorensen',
  'Marchetti'
]

const JOB_TITLES = [
  'Head of Operations',
  'VP of Engineering',
  'Procurement Lead',
  'Director of IT',
  'Chief of Staff',
  'Product Manager',
  'Finance Director',
  'Head of Data',
  'Security Lead',
  'Programme Manager',
  'Head of Marketing',
  'Solutions Architect'
]

export const scalePeople = (): PersonSeed[] => {
  const rows: PersonSeed[] = []

  scaleCompanies().forEach(company => {
    const headcount = company.employees >= 3000 ? 3 : 2

    for (let seat = 0; seat < headcount; seat++) {
      const index = rows.length
      const firstName = FIRST_NAMES[(index * 5) % FIRST_NAMES.length]
      const lastName = LAST_NAMES[(index * 7) % LAST_NAMES.length]

      rows.push({
        id: `per_${37 + index}`,
        firstName,
        lastName,
        email: `${firstName}.${lastName}`.toLowerCase() + `@${company.domainName}`,
        jobTitle: JOB_TITLES[(index * 5) % JOB_TITLES.length],

        ...(index % 3 === 0 ? { avatar: `/images/avatars/avatar-${(index % 20) + 1}.webp` } : {}),
        companyId: company.id,
        isPrimary: seat === 0,
        ...(company.address?.city ? { city: company.address.city } : {}),
        ...(company.address?.country ? { country: company.address.country } : {}),
        accountOwnerId: company.accountOwnerId,

        createdMinutesAgo: company.createdMinutesAgo - 1500 - seat * 2700,
        updatedMinutesAgo: 180 + index * 95
      })
    }
  })

  return rows
}

export const db: PersonSeed[] = [
  {
    id: 'per_1',
    firstName: 'Ada',
    lastName: 'Lovelace',
    email: 'ada.lovelace@airbnb.com',
    phone: '+1 (415) 555-0142',
    jobTitle: 'VP of Engineering',
    avatar: '/images/avatars/avatar-5.webp',
    companyId: 'cmp_1',
    isPrimary: true,
    city: 'San Francisco',
    country: 'United States',
    linkedinUrl: 'linkedin.com/in/adalovelace',
    xUrl: 'x.com/adalovelace',
    accountOwnerId: 'usr_3',
    updatedById: 'usr_2',
    createdMinutesAgo: 21384,
    updatedMinutesAgo: 55
  },
  {
    id: 'per_2',
    firstName: 'Brian',
    lastName: 'Chen',
    email: 'brian.chen@anthropic.com',
    phone: '+1 (415) 555-0193',
    jobTitle: 'Head of Sales',
    avatar: '/images/avatars/avatar-6.webp',
    companyId: 'cmp_2',
    isPrimary: true,
    city: 'San Francisco',
    country: 'United States',
    linkedinUrl: 'linkedin.com/in/brianchen',
    xUrl: 'x.com/brianchen',
    accountOwnerId: 'usr_1',
    updatedById: 'usr_3',
    createdMinutesAgo: 144594,
    updatedMinutesAgo: 322
  },
  {
    id: 'per_3',
    firstName: 'Carla',
    lastName: 'Diaz',
    email: 'carla.diaz@stripe.com',
    phone: '+1 (650) 555-0176',
    jobTitle: 'Account Executive',
    avatar: '/images/avatars/avatar-7.webp',
    companyId: 'cmp_3',
    isPrimary: true,
    city: 'South San Francisco',
    country: 'United States',
    linkedinUrl: 'linkedin.com/in/carladiaz',
    xUrl: 'x.com/carladiaz',
    accountOwnerId: 'usr_1',
    updatedById: 'usr_1',
    createdMinutesAgo: 189657,
    updatedMinutesAgo: 614
  },
  {
    id: 'per_4',
    firstName: 'David',
    lastName: 'Kim',
    email: 'david.kim@figma.com',
    phone: '+1 (415) 555-0128',
    jobTitle: 'Product Manager',
    avatar: '/images/avatars/avatar-8.webp',
    companyId: 'cmp_4',
    isPrimary: true,
    city: 'San Francisco',
    country: 'United States',
    linkedinUrl: 'linkedin.com/in/davidkim',
    xUrl: 'x.com/davidkim',
    accountOwnerId: 'usr_2',
    updatedById: 'usr_4',
    createdMinutesAgo: 87516,
    updatedMinutesAgo: 1017
  },
  {
    id: 'per_5',
    firstName: 'Elena',
    lastName: 'Novak',
    email: 'elena.novak@notion.com',
    phone: '+1 (415) 555-0164',
    jobTitle: 'Marketing Lead',
    avatar: '/images/avatars/avatar-9.webp',
    companyId: 'cmp_5',
    isPrimary: true,
    city: 'San Francisco',
    country: 'United States',
    linkedinUrl: 'linkedin.com/in/elenanovak',
    xUrl: 'x.com/elenanovak',
    accountOwnerId: 'usr_4',
    updatedById: 'usr_2',
    createdMinutesAgo: 57474,
    updatedMinutesAgo: 1365
  },
  {
    id: 'per_6',
    firstName: 'Frank',
    lastName: 'Obi',
    email: 'frank.obi@google.com',
    phone: '+1 (650) 555-0110',
    jobTitle: 'Engineering Director',
    avatar: '/images/avatars/avatar-10.webp',
    companyId: 'cmp_6',
    isPrimary: true,
    city: 'Mountain View',
    country: 'United States',
    linkedinUrl: 'linkedin.com/in/frankobi',
    accountOwnerId: 'usr_1',
    updatedById: 'usr_1',
    createdMinutesAgo: 300807,
    updatedMinutesAgo: 1643
  },
  {
    id: 'per_7',
    firstName: 'Grace',
    lastName: 'Park',
    email: 'grace.park@meta.com',
    phone: '+1 (650) 555-0155',
    jobTitle: 'Technical Recruiter',
    avatar: '/images/avatars/avatar-11.webp',
    companyId: 'cmp_7',
    isPrimary: true,
    city: 'Menlo Park',
    country: 'United States',
    accountOwnerId: 'usr_4',
    updatedById: 'usr_2',
    createdMinutesAgo: 228708,
    updatedMinutesAgo: 2047
  },
  {
    id: 'per_8',
    firstName: 'Henry',
    lastName: 'Ford',
    email: 'henry.ford@microsoft.com',
    phone: '+1 (425) 555-0187',
    jobTitle: 'Solutions Architect',
    avatar: '/images/avatars/avatar-12.webp',
    companyId: 'cmp_8',
    isPrimary: true,
    city: 'Redmond',
    country: 'United States',
    accountOwnerId: 'usr_3',
    updatedById: 'usr_3',
    createdMinutesAgo: 339867,
    updatedMinutesAgo: 677
  },
  {
    id: 'per_9',
    firstName: 'Isla',
    lastName: 'Rossi',
    email: 'isla.rossi@amazon.com',
    jobTitle: 'Operations Manager',
    avatar: '/images/avatars/avatar-13.webp',
    companyId: 'cmp_9',
    isPrimary: true,
    city: 'Seattle',
    country: 'United States',
    accountOwnerId: 'usr_4',
    createdMinutesAgo: 267768,
    updatedMinutesAgo: 2380
  },
  {
    id: 'per_10',
    firstName: 'Jack',
    lastName: 'Ryan',
    email: 'jack.ryan@apple.com',
    phone: '+1 (408) 555-0134',
    jobTitle: 'Design Lead',
    avatar: '/images/avatars/avatar-14.webp',
    companyId: 'cmp_10',
    isPrimary: true,
    city: 'Cupertino',
    country: 'United States',
    linkedinUrl: 'linkedin.com/in/jackryan',
    accountOwnerId: 'usr_2',
    updatedById: 'usr_4',
    createdMinutesAgo: 481059,
    updatedMinutesAgo: 2714
  },
  {
    id: 'per_11',
    firstName: 'Kira',
    lastName: 'Sato',
    email: 'kira.sato@github.com',
    phone: '+1 (415) 555-0166',
    jobTitle: 'Developer Advocate',
    avatar: '/images/avatars/avatar-15.webp',
    companyId: 'cmp_11',
    isPrimary: true,
    city: 'San Francisco',
    country: 'United States',
    accountOwnerId: 'usr_3',
    createdMinutesAgo: 105543,
    updatedMinutesAgo: 378
  },
  {
    id: 'per_12',
    firstName: 'Liam',
    lastName: 'Walsh',
    email: 'liam.walsh@dropbox.com',
    jobTitle: 'Sales Manager',
    avatar: '/images/avatars/avatar-16.webp',
    companyId: 'cmp_12',
    isPrimary: true,
    city: 'San Francisco',
    country: 'United States',
    accountOwnerId: 'usr_1',
    updatedById: 'usr_1',
    createdMinutesAgo: 162621,
    updatedMinutesAgo: 3048
  },
  {
    id: 'per_13',
    firstName: 'Mia',
    lastName: 'Cohen',
    email: 'mia.cohen@shopify.com',
    phone: '+1 (613) 555-0121',
    jobTitle: 'Partnerships Manager',
    avatar: '/images/avatars/avatar-17.webp',
    companyId: 'cmp_13',
    isPrimary: true,
    city: 'Ottawa',
    country: 'Canada',
    linkedinUrl: 'linkedin.com/in/miacohen',
    accountOwnerId: 'usr_4',
    updatedById: 'usr_2',
    createdMinutesAgo: 126567,
    updatedMinutesAgo: 1045
  },
  {
    id: 'per_14',
    firstName: 'Noah',
    lastName: 'Bright',
    email: 'noah.bright@slack.com',
    phone: '+1 (415) 555-0109',
    jobTitle: 'Customer Success Lead',
    avatar: '/images/avatars/avatar-18.webp',
    companyId: 'cmp_14',
    isPrimary: true,
    city: 'San Francisco',
    country: 'United States',
    accountOwnerId: 'usr_1',
    updatedById: 'usr_3',
    createdMinutesAgo: 48465,
    updatedMinutesAgo: 65
  },
  {
    id: 'per_15',
    firstName: 'Olivia',
    lastName: 'Stone',
    email: 'olivia.stone@netflix.com',
    jobTitle: 'Content Strategist',
    avatar: '/images/avatars/avatar-19.webp',
    companyId: 'cmp_15',
    isPrimary: true,
    city: 'Los Gatos',
    country: 'United States',
    accountOwnerId: 'usr_2',
    createdMinutesAgo: 547146,
    updatedMinutesAgo: 3382
  },
  {
    id: 'per_16',
    firstName: 'Paul',
    lastName: 'Adler',
    email: 'paul.adler@adobe.com',
    phone: '+1 (408) 555-0198',
    jobTitle: 'Enterprise Account Executive',
    avatar: '/images/avatars/avatar-20.webp',
    companyId: 'cmp_16',
    isPrimary: true,
    city: 'San Jose',
    country: 'United States',
    linkedinUrl: 'linkedin.com/in/pauladler',
    accountOwnerId: 'usr_1',
    updatedById: 'usr_4',
    createdMinutesAgo: 505089,
    updatedMinutesAgo: 3716
  },
  {
    id: 'per_17',
    firstName: 'Quinn',
    lastName: 'Rivera',
    email: 'quinn.rivera@salesforce.com',
    phone: '+1 (415) 555-0147',
    jobTitle: 'VP of Marketing',
    avatar: '/images/avatars/avatar-5.webp',
    companyId: 'cmp_17',
    isPrimary: true,
    city: 'San Francisco',
    country: 'United States',
    accountOwnerId: 'usr_3',
    createdMinutesAgo: 384930,
    updatedMinutesAgo: 4049
  },
  {
    id: 'per_18',
    firstName: 'Rosa',
    lastName: 'Mendes',
    email: 'rosa.mendes@oracle.com',
    jobTitle: 'Database Lead',
    avatar: '/images/avatars/avatar-6.webp',
    companyId: 'cmp_18',
    isPrimary: true,
    city: 'Austin',
    country: 'United States',
    accountOwnerId: 'usr_4',
    updatedById: 'usr_1',
    createdMinutesAgo: 580194,
    updatedMinutesAgo: 4383
  },
  {
    id: 'per_19',
    firstName: 'Sam',
    lastName: 'Bello',
    email: 'sam.bello@nvidia.com',
    phone: '+1 (408) 555-0173',
    jobTitle: 'Machine Learning Engineer',
    avatar: '/images/avatars/avatar-7.webp',
    companyId: 'cmp_19',
    isPrimary: true,
    city: 'Santa Clara',
    country: 'United States',
    linkedinUrl: 'linkedin.com/in/sambello',
    accountOwnerId: 'usr_1',
    updatedById: 'usr_2',
    createdMinutesAgo: 448011,
    updatedMinutesAgo: 364
  },
  {
    id: 'per_20',
    firstName: 'Tara',
    lastName: 'Singh',
    email: 'tara.singh@uber.com',
    phone: '+1 (415) 555-0119',
    jobTitle: 'Growth Lead',
    avatar: '/images/avatars/avatar-8.webp',
    companyId: 'cmp_20',
    isPrimary: true,
    city: 'San Francisco',
    country: 'United States',
    accountOwnerId: 'usr_3',
    updatedById: 'usr_3',
    createdMinutesAgo: 336861,
    updatedMinutesAgo: 4717
  },
  {
    id: 'per_21',
    firstName: 'Umar',
    lastName: 'Farouk',
    email: 'umar.farouk@airtable.com',
    jobTitle: 'Founder Associate',
    avatar: '/images/avatars/avatar-9.webp',
    companyId: 'cmp_21',
    isPrimary: true,
    city: 'San Francisco',
    country: 'United States',
    accountOwnerId: 'usr_2',
    createdMinutesAgo: 318834,
    updatedMinutesAgo: 5051
  },
  {
    id: 'per_22',
    firstName: 'Vera',
    lastName: 'Klein',
    email: 'vera.klein@datadoghq.com',
    phone: '+1 (212) 555-0164',
    jobTitle: 'SRE Manager',
    avatar: '/images/avatars/avatar-10.webp',
    companyId: 'cmp_23',
    isPrimary: true,
    city: 'New York',
    country: 'United States',
    linkedinUrl: 'linkedin.com/in/veraklein',
    accountOwnerId: 'usr_3',
    updatedById: 'usr_4',
    createdMinutesAgo: 195669,
    updatedMinutesAgo: 6052
  },
  {
    id: 'per_23',
    firstName: 'Will',
    lastName: 'Turner',
    email: 'will.turner@snowflake.com',
    phone: '+1 (406) 555-0152',
    jobTitle: 'Sales Engineer',
    avatar: '/images/avatars/avatar-11.webp',
    companyId: 'cmp_22',
    isPrimary: true,
    city: 'Bozeman',
    country: 'United States',
    accountOwnerId: 'usr_1',
    createdMinutesAgo: 237726,
    updatedMinutesAgo: 5718
  },
  {
    id: 'per_24',
    firstName: 'Xena',
    lastName: 'Blake',
    email: 'xena.blake@mongodb.com',
    phone: '+1 (212) 555-0138',
    jobTitle: 'Field CTO',
    avatar: '/images/avatars/avatar-12.webp',
    companyId: 'cmp_24',
    isPrimary: true,
    city: 'New York',
    country: 'United States',
    linkedinUrl: 'linkedin.com/in/xenablake',
    accountOwnerId: 'usr_2',
    updatedById: 'usr_1',
    createdMinutesAgo: 216693,
    updatedMinutesAgo: 7721
  },
  {
    id: 'per_25',
    firstName: 'Marta',
    lastName: 'Reyes',
    email: 'marta.reyes@airbnb.com',
    phone: '+1 (415) 555-0177',
    jobTitle: 'Director of Procurement',
    avatar: '/images/avatars/avatar-9.webp',
    companyId: 'cmp_1',
    city: 'San Francisco',
    country: 'United States',
    accountOwnerId: 'usr_3',
    updatedById: 'usr_3',

    createdMinutesAgo: 18720,
    updatedMinutesAgo: 30
  },
  {
    id: 'per_26',
    firstName: 'Jerry',
    lastName: 'Halfer',
    email: 'jerry.halfer@airbnb.com',
    phone: '+1 (415) 555-0188',
    jobTitle: 'Head of Platform',
    avatar: '/images/avatars/avatar-10.webp',
    companyId: 'cmp_1',
    city: 'San Francisco',
    country: 'United States',
    accountOwnerId: 'usr_3',

    createdMinutesAgo: 16560,
    updatedMinutesAgo: 30
  },
  {
    id: 'per_27',
    firstName: 'Priya',
    lastName: 'Raman',
    email: 'priya.raman@anthropic.com',
    phone: '+1 (415) 555-0121',
    jobTitle: 'Research Operations Lead',
    avatar: '/images/avatars/avatar-11.webp',
    companyId: 'cmp_2',
    city: 'San Francisco',
    country: 'United States',
    accountOwnerId: 'usr_1',
    updatedById: 'usr_1',
    createdMinutesAgo: 120000,
    updatedMinutesAgo: 30
  },
  {
    id: 'per_28',
    firstName: 'Dana',
    lastName: 'Whitfield',
    email: 'dana.whitfield@stripe.com',
    phone: '+1 (650) 555-0164',
    jobTitle: 'Engineering Manager',
    avatar: '/images/avatars/avatar-12.webp',
    companyId: 'cmp_3',
    city: 'South San Francisco',
    country: 'United States',
    accountOwnerId: 'usr_1',
    updatedById: 'usr_4',
    createdMinutesAgo: 168000,
    updatedMinutesAgo: 30
  },
  {
    id: 'per_29',
    firstName: 'Owen',
    lastName: 'Castillo',
    email: 'owen.castillo@figma.com',
    phone: '+1 (415) 555-0155',
    jobTitle: 'Design Ops Lead',
    avatar: '/images/avatars/avatar-13.webp',
    companyId: 'cmp_4',
    city: 'San Francisco',
    country: 'United States',
    accountOwnerId: 'usr_2',
    updatedById: 'usr_2',
    createdMinutesAgo: 78000,
    updatedMinutesAgo: 30
  },
  {
    id: 'per_30',
    firstName: 'Nathan',
    lastName: 'Osei',
    email: 'nathan.osei@google.com',
    phone: '+1 (650) 555-0132',
    jobTitle: 'Infrastructure Architect',
    avatar: '/images/avatars/avatar-14.webp',
    companyId: 'cmp_6',
    city: 'Mountain View',
    country: 'United States',
    accountOwnerId: 'usr_1',
    createdMinutesAgo: 265000,
    updatedMinutesAgo: 30
  },
  {
    id: 'per_31',
    firstName: 'Lena',
    lastName: 'Fischer',
    email: 'lena.fischer@meta.com',
    phone: '+1 (650) 555-0109',
    jobTitle: 'Procurement Manager',
    avatar: '/images/avatars/avatar-15.webp',
    companyId: 'cmp_7',
    city: 'Menlo Park',
    country: 'United States',
    accountOwnerId: 'usr_4',
    updatedById: 'usr_3',
    createdMinutesAgo: 4369,
    updatedMinutesAgo: 30
  },
  {
    id: 'per_32',
    firstName: 'Sofia',
    lastName: 'Marchetti',
    email: 'sofia.marchetti@microsoft.com',
    phone: '+1 (425) 555-0198',
    jobTitle: 'Program Manager',
    avatar: '/images/avatars/avatar-16.webp',
    companyId: 'cmp_8',
    city: 'Redmond',
    country: 'United States',
    accountOwnerId: 'usr_3',
    updatedById: 'usr_3',
    createdMinutesAgo: 4369,
    updatedMinutesAgo: 30
  },
  {
    id: 'per_33',
    firstName: 'Tomas',
    lastName: 'Lindqvist',
    email: 'tomas.lindqvist@gmail.com',
    phone: '+46 70 555 0142',
    jobTitle: 'Head of Revenue Operations',
    avatar: '/images/avatars/avatar-17.webp',
    city: 'Stockholm',
    country: 'Sweden',
    createdMinutesAgo: 4369,
    updatedMinutesAgo: 30
  },
  {
    id: 'per_34',
    firstName: 'Amara',
    lastName: 'Okafor',
    email: 'amara.okafor@outlook.com',
    phone: '+44 20 5550 0173',
    jobTitle: 'Sales Director',
    avatar: '/images/avatars/avatar-18.webp',
    city: 'London',
    country: 'United Kingdom',
    accountOwnerId: 'usr_2',
    createdMinutesAgo: 4369,
    updatedMinutesAgo: 30
  },
  {
    id: 'per_35',
    firstName: 'Kenji',
    lastName: 'Watanabe',
    email: 'kenji.watanabe@proton.me',
    phone: '+81 3 5550 0126',
    jobTitle: 'CTO',
    avatar: '/images/avatars/avatar-19.webp',
    city: 'Tokyo',
    country: 'Japan',
    createdMinutesAgo: 4369,
    updatedMinutesAgo: 30
  },
  {
    id: 'per_36',
    firstName: 'Isabel',
    lastName: 'Duarte',
    email: 'isabel.duarte@fastmail.com',
    phone: '+351 21 555 0117',
    jobTitle: 'Head of Partnerships',
    avatar: '/images/avatars/avatar-20.webp',
    city: 'Lisbon',
    country: 'Portugal',
    accountOwnerId: 'usr_4',
    createdMinutesAgo: 4369,
    updatedMinutesAgo: 30
  },

  ...scalePeople()
]
