export type EmploymentStatus = "active" | "on_leave" | "suspended" | "terminated";

export type EmployeeRow = {
  id: string;
  user_id: string | null;
  employee_number: string;
  first_name: string;
  last_name: string;
  work_email: string | null;
  personal_email: string | null;
  work_phone: string | null;
  mobile_phone: string | null;
  photo_url: string | null;
  photo_public_id: string | null;
  date_of_birth: string | null;
  gender: string | null;
  marital_status: string | null;
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  state: string | null;
  postal_code: string | null;
  country: string | null;
  emergency_contact_name: string | null;
  emergency_contact_phone: string | null;
  department_id: string | null;
  department_name: string | null;
  job_position_id: string | null;
  job_position_name: string | null;
  manager_id: string | null;
  manager_employee_number: string | null;
  manager_full_name: string | null;
  manager_photo_url: string | null;
  working_schedule_id: string | null;
  working_schedule_name: string | null;
  working_schedule_hours: string | null;
  employment_status: EmploymentStatus;
  hire_date: string | null;
  termination_date: string | null;
  bank_name: string | null;
  bank_account_number: string | null;
  bank_ifsc: string | null;
  tax_identification_number: string | null;
  has_running_contract: boolean;
  created_at: Date;
  updated_at: Date;
};

export type EmployeeWriteData = {
  first_name?: string;
  last_name?: string;
  work_email?: string | null;
  personal_email?: string | null;
  work_phone?: string | null;
  mobile_phone?: string | null;
  date_of_birth?: string | null;
  gender?: string | null;
  marital_status?: string | null;
  address_line1?: string | null;
  address_line2?: string | null;
  city?: string | null;
  state?: string | null;
  postal_code?: string | null;
  country?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  department_id?: string | null;
  job_position_id?: string | null;
  manager_id?: string | null;
  working_schedule_id?: string | null;
  employment_status?: EmploymentStatus;
  hire_date?: string | null;
  bank_name?: string | null;
  bank_account_number?: string | null;
  bank_ifsc?: string | null;
  tax_identification_number?: string | null;
};
