'use client'
import DataConnectionNotice from '@/features/hr/components/data-connection-notice'
import { useState } from 'react'
import Link from 'next/link'
import { Button } from '@/features/nexacrm/components/ui/button'
import { Card } from '@/features/nexacrm/components/ui/card'
import { TableSearch } from '@/features/nexacrm/components/data-table/table-search'
import { Choice } from '@/features/hr/components/form'
import { usePayrollStore } from '../store'
import { usePayrollPermissions } from '../permissions'
import { PAYRUN_STATUSES } from '../types'
import { formatRecordCount } from '@/features/nexacrm/lib/record-count'
import { AccessDenied, Heading, SlipTable } from './shared'
export default function PayslipsView(){const slips=usePayrollStore(s=>s.payslips);const {canReadPayslips,canReadPayruns}=usePayrollPermissions();const [search,setSearch]=useState('');const [status,setStatus]=useState('all');const filtered=slips.filter(s=>(status==='all'||s.status===status)&&`${s.employeeName} ${s.employeeEmail} ${s.structureName} ${s.startDate} ${s.endDate} ${PAYRUN_STATUSES[s.status]}`.toLowerCase().includes(search.trim().toLowerCase()));if(!canReadPayslips)return <AccessDenied/>;return <div className="flex min-h-full flex-col"><Heading title="Payslips">{canReadPayruns&&<Button size="sm" variant="outline" render={<Link href="/payroll"/>}>Payruns</Button>}</Heading><div className="space-y-4 py-4"><DataConnectionNotice /><div className="flex flex-wrap items-center gap-3"><TableSearch className="w-full sm:w-64" value={search} placeholder="Search employee, structure, or period…" onValueChange={setSearch}/><div className="w-40"><Choice id="payslip-status" value={status} onChange={setStatus} options={[{value:'all',label:'All statuses'},...Object.entries(PAYRUN_STATUSES).map(([value,label])=>({value,label}))]}/></div></div><Card className="gap-0 overflow-hidden py-0"><SlipTable slips={filtered} searchable={false}/><div className="text-muted-foreground border-t px-4 py-3 text-sm">{formatRecordCount(filtered.length,'payslip')}</div></Card></div></div>}
